### ISSUE TITLE
Enhancement: expose Chuck_Event to chugins

### ISSUE THREAD

**Issue by dbadb** [ccrma/chuck#235]
I'm experimenting with chugin-originated event triggering, would like this code to work:

```ck
// approach 1: external Event passed to chugin
Event evt;
MyEventChugin chg;
chg.Doit(evt); // pass Event to chugin
evt => now;  // wait for chugin to respond
// proceed here...

// approach 2: chugin as Event subclass
MyEventChugin chg;
chg.Doit();
chg => now;
// proceed here.
```

Turns out this appears to almost work already!

Approach 1
1. Doit accepts `Chuck_Object *`
2. cast `Chuck_Object *` to `Chuck_Event *`
3. Doit performs work, perhaps in another thread. When complete evt->broadcast_local() allows evt's clients to proceed.

Approach 2 
1. Doit "subclasses"  Event
2. Doit overrides parent "can_wait" method
3. Doit performs work, perhaps in another thread. Calls ((Chuck_Event *)SELF)->broadcast_local().

Only issue is that Chuck_Event::broadcast_local is a concrete reference and the result is a link error.  The "fix" is simply to make Chuck_Event::broadcast_local a virtual method and this link issue is resolved.  I verified that this one-line fix works on 3 platforms.

Potential concerns:

- probably should make all variants of broadcast and signal virtual, so the change would total around 4-6 lines.
- Approach 1: chugin could hold onto ref to Event after it goes out of scope.  This could either be remedied by exposing more Chuck_Object refcount functionality or simply by documenting the invalid use-cases.  Approach 2 doesn't suffer from this issue.
- this request might be the tip of the iceberg.  In my case, though, it appears to be both necessary and sufficient so far.
- changing the Chuck_Event methods to virtual increases the method-dispatch overhead.  I think this is a non-issue
  since `broadcast_local `(and friends) are far from any performance hotspots (afaict).

I'll be happy to make a pull request for this change if the chuck-team approves/requests.  Of course, it's trivial enough that chuck-team could simply make the change. Here's a diff fwiw:

```sh
% diff --git a/src/core/chuck_oo.h b/src/core/chuck_oo.h
index 4505db0..be9ff5d 100644
--- a/src/core/chuck_oo.h
+++ b/src/core/chuck_oo.h
@@ -489,8 +489,8 @@ struct Chuck_Event : Chuck_Object
 {
 public:
     // signal/broadcast "local" -- signal ChucK Events
-    void signal_local();
-    void broadcast_local();
+    virtual void signal_local();
+    virtual void broadcast_local();

     void wait( Chuck_VM_Shred * shred, Chuck_VM * vm );
     t_CKBOOL remove( Chuck_VM_Shred * shred );
```

thx! Dana

**Comment by nshaheed** [comment]
Thanks for investigating this Dana! 

I'm not so sure making the broadcast/signal methods makes sense as a long-term solution to this issue. I'd agree that it's probably not a big issue regarding performance by making just the signal and broadcast methods virtual, but it's also not a general solution to the problem of needing to call methods of chuck-defined objects within chugins. In order to avoid patchwork solutions that make the codebase inconsistent and harder to maintain, we'd have to make every object method virtual. This is both a massive change to make and would probably have a meaningful performance impact with *every* class method needing dynamic dispatch. It also doesn't always make sense, because there's no guarantee of a 1:1 correspondence of the object method in chuck and the c++ implementation.

I think the better solution is to expand the [chuck_dl_api](https://github.com/ccrma/chuck/blob/main/src/core/chuck_dl.h#L657) to include calling object methods (and subsequently handling in the context of the vm). #234 is relevant to this and maybe we can further expand on this in later PR to facilitate what you're trying to do.

In the meantime, I think I have a workaround that would help you accomplish what you need to do: I've been working on a [Patch chugin](https://github.com/nshaheed/chugins/blob/patch_chugin/Patch/Patch.cpp) that take the input signal to `Patch` and pipes it as input to an object method every tick (the top of the cpp file has an example). The `connect` method has an example of how to lookup object methods, and the `tick` method shows how to call the function. This should let you call broadcast event from within your chugin! Also if you're able to share, I'd be interested in seeing the code for my own purposes :)


Thanks,
Nick

**Comment by dbadb** [comment]
Hey Nick - I completely concur with the slippery-slopedness of the request to expose ChucK inner workings to chugins.  I like your idea embodied in the Patch chugin and will give it a try and report back.

**Comment by dbadb** [comment]
Hey Nick - I've now grokked the approach you used in Patch.cpp and it's a cool trick indeed!  

That said, from my POV, the same concerns about object-exposure exists in your implementation.  Perhaps, even deeper ones.  The goal for any plugin interface is to separate interface from implementation in such a way as to ensure that plugins continue to work even when chuck's private innards undergo significant change.  It might be said that chugins have never reached that lofty goal insofar as the entire set of chuck headers are available to the chugin developer.  It is because of this that you can traipse through the Chuck_Object and Chuck_VM data structures.

As you point out, the purpose of the chuck_dl_api is to abstract acceptable practices behind this interface.   Still, its current state suggests that it was designed to provide member-variable access and in our cases we want to invoke chuck-object methods.  Of course every method takes its unique set of parameters and so making a generic method-invocation interface is non-trivial or at least hard to appear elegant.

So I guess this thread may simply be an acknowledgement that the horse (for a plugin interface to ensure forward-compatible plugins) has already left the barn.

**Comment by nshaheed** [comment]
Yes, I agree about this approach not being ideal. My intent wasn't to offer an end-all solution, just a hacky one that doesn't require the hackiness to bubble up to the interface :)

However, I think my approach in Patch has the seeds of how to approach the backend of a method caller api. I'm not sure elegant will be the end result, but I think it would at least be consistent with the rest of the chugin interfaces.

I'm going to close this bug, but I opened #239 to track this feature

**Comment by dbadb** [comment]
Nick - I went ahead and implemented your approach in my experimental chugin.  Seems to work!

If you are interested in seeing it (and its use for subclassing Event via chugin), see [here](https://github.com/cannerycoders/chugins/tree/main/DbSampleMgr)
