### ISSUE TITLE
Test 86 failing on M1s

### ISSUE THREAD

**Issue by mulshine** [ccrma/chuck#246]
Test 86 failing on M1s. May need to disable (temporarily or longterm).

**Comment by nshaheed** [comment]
If we decide to keep the test, it will depend on #247 being implemented

**Comment by gewang** [comment]
we have determined that the discrepancies in behavior is due to the -ffast-math compiler flag (which enables a few specific aggro arm-based math operations, along with instilling some assumptions, like all floats are finite, which will cause Math.isinf to always return false)

fast-math has been disabled by default in the source; also all distributions moving forward will ship without this flag enabled. 86.ck has been restored in 78d6095

more context:
https://stackoverflow.com/questions/7420665/what-does-gccs-ffast-math-actuall$
https://simonbyrne.github.io/notes/fastmath/
