### ISSUE TITLE
Machine.add() introducing lag in audio

### ISSUE THREAD

**Issue by mhzareei** [ccrma/chuck#346]
Hi team,
I've just noticed that in the new update, if you use Machine.add() while there's audio running in the same or another thread, it causes a hiccup/lag in the audio (upon launching the new thread using Machine.add() - even if the new thread is an empty file). 

The issue is related to machine.add() and manually adding the shreds is absolutely fine. 

I'm running this on a macbook pro 2017 (2.9 GHz Quad-Core Intel Core i7), Ventura ,Version 13.3.1 (a).
Issue is not limited to miniAudicle and happens in terminal too. 

I've got the latest update. But just checked on an older version (1.3.7 I think) and it was fine on that one. 

I've used a wide range of examples. But the simples one would be: Running a SinOsc in a thread, and then having a second thread that launches a third thread (and empty file, or a print command) using Machine.add().

Thanks,
Mo

**Comment by gewang** [comment]
acknowledged and thank you for reporting; will investigate and report back

**Comment by gewang** [comment]
traced the issue to commit 67a6fc3 in 1.5.0.4, and has to do with new filepath expansion (for resolving `~` and `~[username`) and the underlying `wordexp()` implementation seemingly perform blocking IO. We have added two partial fixes so far:
1) `Machine.add()` will no longer call expand path if no `~` is detected in the file path (commit 3e9737a)
```
// this should no longer cause audio click IF path has no `~` in it
Machine.add( "bar.ck" );
```
2) for filepaths with `~`, we added a `string FileIO.expandPath( p )` so that `~` or `~[username]` could be expanded at the very beginning to an absolute path without `~` (commit 7d81709)
```
// make sound
SinOsc foo => dac;
440 => foo.freq;

// expand path with ~ ahead of time, to avoid click later with Machine.add()
FileIO.expandPath( "~/code/b.ck" ) => string path;

// wait a bit
.5::second => now;

// add 
Machine.add( path );

// wait more
3::second => now;
```
if you'd like, please feel free test on 7d81709 and let us know how things go? thank you!

**Comment by mhzareei** [comment]
Excellent! Thanks.

**Comment by gewang** [comment]
FYI chuck 1.5.1.3 is [released](https://chuck.stanford.edu/release/), containing this fix

**Comment by mhzareei** [comment]
Perfect. Works great! Thanks again!
