### ISSUE TITLE
Basic Oscillator UGens can't be use Envelope as signal input with sync 0

### ISSUE THREAD

**Issue by jwmatthys** [ccrma/chuck#38]
The documentation says that SinOsc.sync(0) syncs the frequency to input. This works with oscillators as input, but not Envelope.
```c
Envelope e => SinOsc s => dac;
220 => e.value;
440 => e.target;
minute => e.duration;
minute => now;
```

But s's frequency remains at zero.

Using an envelope as freq input would greatly simplify glissando.

**Comment by spencersalazar** [comment]
ChucK envelopes work by applying their value to their input. Since this envelope has no input, its value is applied to 0, resulting in constant 0 output. You can try feeding a constant:

    Step one => Envelope e => SinOsc s => dac;
    1 => one.next;

which should give you the desired result. However it might be nice if Envelope/ADSR detected if they have input or not, and would output the current envelope value if there is no source connected.

**Comment by jwmatthys** [comment]
Ah! Of course, Envelope is a signal multiplier! Thank you.

Perhaps an example using Step => Envelope => SinOsc for glissando could go in the basic examples?
